server:
  port: 8087

jwt:
  secret: 1e4df1d8ccb556e6a6c8c3933f24547ad356fac795e0b83515fb11c34868382f
  expiration: 864000000

spring:
  application:
      name: "MsAuth"
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms_auth_db   # mongodb://tads:tads@localhost:27017/ms_auth_db?authSource=admin

  docker:
    compose:
      enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: tads
    password: tads


endpoints:
  cliente: "http://localhost:8082/api/clientes"


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    disable-swagger-default-url: true

