spring:
  application:
      name: "MsAuth"
  data:
    mongodb:
      uri: mongodb://localhost:27017/ms_auth_db

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    disable-swagger-default-url: true
