spring:
  application:
      name: "MsComposition"

server:
  port: 8086

endpoints:
  cliente: "http://localhost:8082/api/clientes"
  conta: "http://localhost:8083/api/contas"
  gerente: "http://localhost:8084/api/gerentes"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    disable-swagger-default-url: true
