server:
  port: 8088

spring:
  docker:
    compose:
      enabled: false

  application:
      name: "MsSaga"

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: tads
    password: tads
