services:

  # SERVIÇOS PRINCIPAIS
  postgres-db:
    image: postgres:14
    container_name: bantads-postgres
    environment:
      POSTGRES_USER: tads
      POSTGRES_PASSWORD: tads
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql #mapeamento do roteiro de criação

  mongo:
    image: mongo:latest
    container_name: bantads-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo-db.js:/docker-entrypoint-initdb.d/init-mongo-db.js:ro
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: tads
      ME_CONFIG_BASICAUTH_PASSWORD: tads
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    links:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bantads-rabbitmq
    ports:
      - "5672:5672" # Comunicação
      - "15672:15672" # Painel
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=tads
      - RABBITMQ_DEFAULT_PASS=tads

  # MICROSSERVIÇOS

  ms-cliente:
    build: ./ms-cliente
    container_name: ms-cliente
    ports:
      - "8082:8082"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ms_cliente_db
    depends_on:
      - rabbitmq
      - postgres-db

  ms-conta:
    build: ./ms-conta
    container_name: ms-conta
    ports:
      - "8083:8083"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_COMMAND_URL=jdbc:postgresql://postgres-db:5432/ms_conta_cud_db
      - SPRING_DATASOURCE_QUERY_URL=jdbc:postgresql://postgres-db:5432/ms_conta_r_db
    depends_on:
      - rabbitmq
      - postgres-db

  ms-gerente:
    build: ./ms-gerente
    container_name: ms-gerente
    ports:
      - "8084:8084"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ms_gerente_db
    depends_on:
      - rabbitmq
      - postgres-db

  ms-composition:
    build: ./ms-composition
    container_name: ms-composition
    environment:
      - CLIENTE_URL=http://ms-cliente:8082/api/clientes
      - CONTA_URL=http://ms-conta:8083/api/contas
      - GERENTE_URL=http://ms-gerente:8084/api/gerentes
    ports:
      - "8086:8086"

  ms-auth:
    build: ./ms-auth
    container_name: ms-auth
    ports:
      - "8087:8087"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/ms_auth_db
      - CLIENTE_URL=http://ms-cliente:8082/api/clientes
    depends_on:
      - rabbitmq
      - mongo

  ms-saga:
    build: ./ms-saga
    container_name: ms-saga
    ports:
      - "8088:8088"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  ms-email:
    build: ./ms-email
    container_name: ms-email
    ports:
      - "8089:8089"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  api-gateway:
    build: ../api-gateway/
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - CLIENTE_SERVICE_URL=http://ms-cliente:8082/api/clientes
      - CONTA_SERVICE_URL=http://ms-conta:8083/api/contas
      - GERENTE_SERVICE_URL=http://ms-gerente:8084/api/gerentes
      - COMPOSITION_SERVICE_URL=http://ms-composition:8086/api
      - AUTH_SERVICE_URL=http://ms-auth:8087/api/auth

    depends_on:
      - ms-cliente
      - ms-conta
      - ms-gerente
      - ms-auth
      - ms-composition

  bantads-frontend:
    build: ../../
    container_name: bantads-frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway


volumes:
  pg_data:
  mongo_data:
  rabbit_data:
