services:
  postgres-db:
    image: postgres:14
    container_name: bantads-postgres
    environment:
      POSTGRES_USER: tads
      POSTGRES_PASSWORD: tads
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql #mapeamento do roteiro de criação

  mongo:
    image: mongo:latest
    container_name: bantads-mongodb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: tads
#      MONGO_INITDB_ROOT_PASSWORD: tads
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: tads
      ME_CONFIG_BASICAUTH_PASSWORD: tads
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    links:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bantads-rabbitmq
    ports:
      - "5672:5672" # Comunicação
      - "15672:15672" # Painel
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=tads
      - RABBITMQ_DEFAULT_PASS=tads

volumes:
  pg_data:
  mongo_data:
  rabbit_data:
